### ISSUE TITLE
when i try to use this command "cd kernels/selective_scan && pip install ."  i got the following issue. 

### ISSUE THREAD

**Issue by chira98** [ChenHongruixuan/MambaCD#62]
```Processing /userhomes/17/CD/MambaCD/kernels/selective_scan
Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in /userhomes/17/anaconda3/envs/vmam/lib/python3.8/site-packages (from selective_scan==0.0.2) (2.4.0)
Requirement already satisfied: packaging in /userhomes/17/anaconda3/envs/vmam/lib/python3.8/site-packages (from selective_scan==0.0.2) (24.1)
Collecting ninja (from selective_scan==0.0.2)
Using cached ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (5.3 kB)
Collecting einops (from selective_scan==0.0.2)
Using cached einops-0.8.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: filelock in /userhomes/17/anaconda3/envs/vmam/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /userhomes/17/anaconda3/envs/vmam/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (4.11.0)
Requirement already satisfied: sympy in /userhomes/17/anaconda3/envs/vmam/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (1.13.2)
Requirement already satisfied: networkx in /userhomes/17/anaconda3/envs/vmam/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (3.1)
Requirement already satisfied: jinja2 in /userhomes/17/anaconda3/envs/vmam/lib/python3.8/site-packages (from torch->selective_scan==0.0.2) (3.1.4)
Collecting fsspec (from torch->selective_scan==0.0.2)
Using cached fsspec-2024.6.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /userhomes/17/anaconda3/envs/vmam/lib/python3.8/site-packages (from jinja2->torch->selective_scan==0.0.2) (2.1.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /userhomes/17/anaconda3/envs/vmam/lib/python3.8/site-packages (from sympy->torch->selective_scan==0.0.2) (1.3.0)
Using cached einops-0.8.0-py3-none-any.whl (43 kB)
Using cached ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (307 kB)
Using cached fsspec-2024.6.1-py3-none-any.whl (177 kB)
Building wheels for collected packages: selective_scan
Building wheel for selective_scan (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py bdist_wheel did not run successfully.
│ exit code: 1
╰─> [32 lines of output]

torch.version = 2.4.0

CUDA_HOME = /userhomes/17/anaconda3/envs/vmam

running bdist_wheel
/userhomes/17/anaconda3/envs/vmam/lib/python3.8/site-packages/torch/utils/cpp_extension.py:495: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
warnings.warn(msg.format('we could not find ninja.'))
running build
running build_ext
/userhomes/17/anaconda3/envs/vmam/lib/python3.8/site-packages/torch/utils/cpp_extension.py:424: UserWarning: There are no g++ version bounds defined for CUDA version 12.1
warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
building 'selective_scan_cuda_core' extension
creating build
creating build/temp.linux-x86_64-cpython-38
creating build/temp.linux-x86_64-cpython-38/csrc
creating build/temp.linux-x86_64-cpython-38/csrc/selective_scan
creating build/temp.linux-x86_64-cpython-38/csrc/selective_scan/cus
gcc -pthread -B /userhomes/17/anaconda3/envs/vmam/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/userhomes/17/CD/MambaCD/kernels/selective_scan/csrc/selective_scan -I/userhomes/17/anaconda3/envs/vmam/lib/python3.8/site-packages/torch/include -I/userhomes/17/anaconda3/envs/vmam/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/userhomes/17/anaconda3/envs/vmam/lib/python3.8/site-packages/torch/include/TH -I/userhomes/17/anaconda3/envs/vmam/lib/python3.8/site-packages/torch/include/THC -I/userhomes/17/anaconda3/envs/vmam/include -I/userhomes/17/anaconda3/envs/vmam/include/python3.8 -c csrc/selective_scan/cus/selective_scan.cpp -o build/temp.linux-x86_64-cpython-38/csrc/selective_scan/cus/selective_scan.o -O3 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="gcc" -DPYBIND11_STDLIB="libstdcpp" -DPYBIND11_BUILD_ABI="cxxabi1011" -DTORCH_EXTENSION_NAME=selective_scan_cuda_core -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/userhomes/17/anaconda3/envs/vmam/bin/nvcc -I/userhomes/17/CD/MambaCD/kernels/selective_scan/csrc/selective_scan -I/userhomes/17/anaconda3/envs/vmam/lib/python3.8/site-packages/torch/include -I/userhomes/17/anaconda3/envs/vmam/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/userhomes/17/anaconda3/envs/vmam/lib/python3.8/site-packages/torch/include/TH -I/userhomes/17/anaconda3/envs/vmam/lib/python3.8/site-packages/torch/include/THC -I/userhomes/17/anaconda3/envs/vmam/include -I/userhomes/17/anaconda3/envs/vmam/include/python3.8 -c csrc/selective_scan/cus/selective_scan_core_bwd.cu -o build/temp.linux-x86_64-cpython-38/csrc/selective_scan/cus/selective_scan_core_bwd.o -D__CUDA_NO_HALF_OPERATORS -D__CUDA_NO_HALF_CONVERSIONS_ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT162_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=selective_scan_cuda_core -D_GLIBCXX_USE_CXX11_ABI=0
/usr/include/cub/detail/device_synchronize.cuh(53): error: identifier "__cudaDeviceSynchronizeDeprecationAvoidance" is undefined
result = __cudaDeviceSynchronizeDeprecationAvoidance();
^

1 error detected in the compilation of "csrc/selective_scan/cus/selective_scan_core_bwd.cu".
error: command '/userhomes/17/anaconda3/envs/vmam/bin/nvcc' failed with exit code 255
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for selective_scan
Running setup.py clean for selective_scan
Failed to build selective_scan
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (selective_scan) ```


I found similar issues and solutions, but none of them worked for me.
I use,
 Python version: 3.8
 CUDA version: 12.1
 PyTorch version: 2.4.0

Please help on how to resolve this issue. Thank you!

**Comment by chira98** [comment]
Thank you for pointing that out! Could you please let me know which versions of Python, PyTorch, and the other relevant libraries you're using? I'll make sure to match my setup with yours. Thanks for your help!

**Comment by ChenHongruixuan** [comment]
Hi @chira98 ,

We have attached the specific version of these libraries we use as follows. After the python version is the same as ours (it's best to create a virtual environment), I'd recommend that you follow our instructions and reinstall it from the beginning.

# Name                    Version                   Build  Channel
python                    3.10.13              h955ad1f_0
torch                     2.2.1                    pypi_0    pypi
torchaudio                2.2.1                    pypi_0    pypi
torchvision               0.17.1                   pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.19.3                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.4.99                  pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi

Please kindly consider giving this repository a star if our code helps you in your research, thank you very much!

Best,

**Comment by ChenHongruixuan** [comment]
Hi @chira98 ,

May I ask did you solve your issue? If solved, could you reply to this message and briefly explain how it was resolved? That way it can be used as a reference for peers who come across the same problem later on. Thank you very much!

Best,

**Comment by chira98** [comment]
@ChenHongruixuan  Unfortunately, I haven't been able to resolve the issue yet. I followed the installation steps and tried installing the versions you given, but I still encounter the same error.

**Comment by ChenHongruixuan** [comment]
Hi @chira98 , it's weird. Can you tell me the model of your GPU and your current NVIDIA driver version?

**Comment by chira98** [comment]
@ChenHongruixuan  GPU model : Quadro GV100 ,NVIDIA driver version: 535.183.01

**Comment by ChenHongruixuan** [comment]
Hi @chira98 , we are sorry to say that we can't diagnose the exact cause just by doing this. We would recommend you to refer to the issue section of VMamba to see relevant solutions (https://github.com/MzeroMiko/VMamba/issues).
